### ISSUE TITLE
Test dataset

### ISSUE THREAD

**Issue by zo0z** [Ancestry/cehg16-workshop#1]
Hi!
Thank you for the great effort providing this material on line! I'm trying to use your extracted dataset to test an algorithm I'm working on, but I'm finding it challenging to track the numbers...

Counting the number of lines in 1kg_hgdp.fam, shows that there are 927 1000G sample and 1829 HGDP samples, making a total of 2756... The numbers on the READme is a bit different, and I wanted to check where that is coming from...

Thank you once more...

Regards,
Azza

**Comment by pcarbo** [comment]
Hi Azza, 

Thank you for the note. I will check these numbers---perhaps there is a mistake somewhere in my description. I should be able to get to this on Wednesday or Thursday next week.

Peter

**Comment by zo0z** [comment]
Thank you very much! 
Any detail you can share on data pruning and cleaning would be really great...

**Comment by pcarbo** [comment]
I checked and indeed there are 2,756 samples total:

```
> wc -l 1kg_hgdp.fam 
2756
```

The number of HGDP samples is 940:

```
grep HGDP 1kg_hgdp.fam | wc -l
940
```

I noticed one mistake in the README where I gave the incorrect number of 1000 Genomes samples, so I fixed that. If you notice any other mistakes, please let me know.

Thanks!
Peter
