### ISSUE TITLE
Sample Data Sources

### ISSUE THREAD

**Issue by herroannekim** [Ancestry/cehg16-workshop#2]
Where were your 2,756 samples from?  The naming scheme for your data `hgdp` suggests that they came from the [Human Genome Diversity Project, but that source only has 1,043](http://www.hagsc.org/hgdp/).  As of May, the [1000Genomes project has more than 2,600 samples](https://academic.oup.com/gigascience/article-lookup/doi/10.1093/gigascience/gix038), but is that where the other samples came from when this workshop was created in April 2016?  Did the data ever incorporate the [1,301 samples of the HapMap project](http://www.sanger.ac.uk/resources/downloads/human/hapmap3.html)?  Thanks!

**Comment by pcarbo** [comment]
Hi @herroannekim:

From the README:

> The final combined data set containes genotypes at 162,645 SNPs and 2,756 
> samples---940 HGDP "unrelated" samples (see here) and 1,816 samples from 
> the 1000 Genomes Project.

The 1,816 samples are a subset of the 2,318 samples from the 1000 Genomes Project downloaded  [here](ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/hd_genotype_chip/ALL.chip.omni_broad_sanger_combined.20140818.snps.genotypes.vcf.gz).

I don't recall the exact reasons for removing the 502 samples; you could potentially use all 1000 Genomes samples, noting that some of them are more closely related according to [this table](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/20140625_related_individuals.txt).

No HapMap samples are included in this data set.

**Comment by herroannekim** [comment]
Thanks!
